// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: github.com/heroiclabs/nakama/apigrpc/apigrpc.proto

#include "github.com/heroiclabs/nakama/apigrpc/apigrpc.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace nakama {
namespace api {
}  // namespace api
}  // namespace nakama
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_github_2ecom_2fheroiclabs_2fnakama_2fapigrpc_2fapigrpc_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_github_2ecom_2fheroiclabs_2fnakama_2fapigrpc_2fapigrpc_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_github_2ecom_2fheroiclabs_2fnakama_2fapigrpc_2fapigrpc_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_github_2ecom_2fheroiclabs_2fnakama_2fapigrpc_2fapigrpc_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_github_2ecom_2fheroiclabs_2fnakama_2fapigrpc_2fapigrpc_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n2github.com/heroiclabs/nakama/apigrpc/a"
  "pigrpc.proto\022\nnakama.api\032\034google/api/ann"
  "otations.proto\032\025google/api/http.proto\032\033g"
  "oogle/protobuf/empty.proto\032,protoc-gen-o"
  "penapiv2/options/openapiv2.proto\032.protoc"
  "-gen-openapiv2/options/annotations.proto"
  "\0321github.com/heroiclabs/nakama-common/ap"
  "i/api.proto2\363E\n\006Nakama\022W\n\nAddFriends\022\035.n"
  "akama.api.AddFriendsRequest\032\026.google.pro"
  "tobuf.Empty\"\022\202\323\344\223\002\014\"\n/v2/friend\022k\n\rAddGr"
  "oupUsers\022 .nakama.api.AddGroupUsersReque"
  "st\032\026.google.protobuf.Empty\" \202\323\344\223\002\032\"\030/v2/"
  "group/{group_id}/add\022\204\001\n\016SessionRefresh\022"
  "!.nakama.api.SessionRefreshRequest\032\023.nak"
  "ama.api.Session\":\202\323\344\223\002 \"\033/v2/account/ses"
  "sion/refresh:\001*\222A\021b\017\n\r\n\tBasicAuth\022\000\022h\n\rS"
  "essionLogout\022 .nakama.api.SessionLogoutR"
  "equest\032\026.google.protobuf.Empty\"\035\202\323\344\223\002\027\"\022"
  "/v2/session/logout:\001*\022\223\001\n\021AuthenticateAp"
  "ple\022$.nakama.api.AuthenticateAppleReques"
  "t\032\023.nakama.api.Session\"C\202\323\344\223\002)\"\036/v2/acco"
  "unt/authenticate/apple:\007account\222A\021b\017\n\r\n\t"
  "BasicAuth\022\000\022\226\001\n\022AuthenticateCustom\022%.nak"
  "ama.api.AuthenticateCustomRequest\032\023.naka"
  "ma.api.Session\"D\202\323\344\223\002*\"\037/v2/account/auth"
  "enticate/custom:\007account\222A\021b\017\n\r\n\tBasicAu"
  "th\022\000\022\226\001\n\022AuthenticateDevice\022%.nakama.api"
  ".AuthenticateDeviceRequest\032\023.nakama.api."
  "Session\"D\202\323\344\223\002*\"\037/v2/account/authenticat"
  "e/device:\007account\222A\021b\017\n\r\n\tBasicAuth\022\000\022\223\001"
  "\n\021AuthenticateEmail\022$.nakama.api.Authent"
  "icateEmailRequest\032\023.nakama.api.Session\"C"
  "\202\323\344\223\002)\"\036/v2/account/authenticate/email:\007"
  "account\222A\021b\017\n\r\n\tBasicAuth\022\000\022\234\001\n\024Authenti"
  "cateFacebook\022\'.nakama.api.AuthenticateFa"
  "cebookRequest\032\023.nakama.api.Session\"F\202\323\344\223"
  "\002,\"!/v2/account/authenticate/facebook:\007a"
  "ccount\222A\021b\017\n\r\n\tBasicAuth\022\000\022\275\001\n\037Authentic"
  "ateFacebookInstantGame\0222.nakama.api.Auth"
  "enticateFacebookInstantGameRequest\032\023.nak"
  "ama.api.Session\"Q\202\323\344\223\0027\",/v2/account/aut"
  "henticate/facebookinstantgame:\007account\222A"
  "\021b\017\n\r\n\tBasicAuth\022\000\022\242\001\n\026AuthenticateGameC"
  "enter\022).nakama.api.AuthenticateGameCente"
  "rRequest\032\023.nakama.api.Session\"H\202\323\344\223\002.\"#/"
  "v2/account/authenticate/gamecenter:\007acco"
  "unt\222A\021b\017\n\r\n\tBasicAuth\022\000\022\226\001\n\022Authenticate"
  "Google\022%.nakama.api.AuthenticateGoogleRe"
  "quest\032\023.nakama.api.Session\"D\202\323\344\223\002*\"\037/v2/"
  "account/authenticate/google:\007account\222A\021b"
  "\017\n\r\n\tBasicAuth\022\000\022\223\001\n\021AuthenticateSteam\022$"
  ".nakama.api.AuthenticateSteamRequest\032\023.n"
  "akama.api.Session\"C\202\323\344\223\002)\"\036/v2/account/a"
  "uthenticate/steam:\007account\222A\021b\017\n\r\n\tBasic"
  "Auth\022\000\022k\n\rBanGroupUsers\022 .nakama.api.Ban"
  "GroupUsersRequest\032\026.google.protobuf.Empt"
  "y\" \202\323\344\223\002\032\"\030/v2/group/{group_id}/ban\022a\n\014B"
  "lockFriends\022\037.nakama.api.BlockFriendsReq"
  "uest\032\026.google.protobuf.Empty\"\030\202\323\344\223\002\022\"\020/v"
  "2/friend/block\022V\n\013CreateGroup\022\036.nakama.a"
  "pi.CreateGroupRequest\032\021.nakama.api.Group"
  "\"\024\202\323\344\223\002\016\"\t/v2/group:\001*\022]\n\rDeleteFriends\022"
  " .nakama.api.DeleteFriendsRequest\032\026.goog"
  "le.protobuf.Empty\"\022\202\323\344\223\002\014*\n/v2/friend\022c\n"
  "\013DeleteGroup\022\036.nakama.api.DeleteGroupReq"
  "uest\032\026.google.protobuf.Empty\"\034\202\323\344\223\002\026*\024/v"
  "2/group/{group_id}\022\207\001\n\027DeleteLeaderboard"
  "Record\022*.nakama.api.DeleteLeaderboardRec"
  "ordRequest\032\026.google.protobuf.Empty\"(\202\323\344\223"
  "\002\"* /v2/leaderboard/{leaderboard_id}\022o\n\023"
  "DeleteNotifications\022&.nakama.api.DeleteN"
  "otificationsRequest\032\026.google.protobuf.Em"
  "pty\"\030\202\323\344\223\002\022*\020/v2/notification\022v\n\024DeleteS"
  "torageObjects\022\'.nakama.api.DeleteStorage"
  "ObjectsRequest\032\026.google.protobuf.Empty\"\035"
  "\202\323\344\223\002\027\032\022/v2/storage/delete:\001*\022H\n\005Event\022\021"
  ".nakama.api.Event\032\026.google.protobuf.Empt"
  "y\"\024\202\323\344\223\002\016\"\t/v2/event:\001*\022N\n\nGetAccount\022\026."
  "google.protobuf.Empty\032\023.nakama.api.Accou"
  "nt\"\023\202\323\344\223\002\r\022\013/v2/account\022L\n\010GetUsers\022\033.na"
  "kama.api.GetUsersRequest\032\021.nakama.api.Us"
  "ers\"\020\202\323\344\223\002\n\022\010/v2/user\022S\n\013Healthcheck\022\026.g"
  "oogle.protobuf.Empty\032\026.google.protobuf.E"
  "mpty\"\024\202\323\344\223\002\016\022\014/healthcheck\022\177\n\025ImportFace"
  "bookFriends\022(.nakama.api.ImportFacebookF"
  "riendsRequest\032\026.google.protobuf.Empty\"$\202"
  "\323\344\223\002\036\"\023/v2/friend/facebook:\007account\022v\n\022I"
  "mportSteamFriends\022%.nakama.api.ImportSte"
  "amFriendsRequest\032\026.google.protobuf.Empty"
  "\"!\202\323\344\223\002\033\"\020/v2/friend/steam:\007account\022d\n\tJ"
  "oinGroup\022\034.nakama.api.JoinGroupRequest\032\026"
  ".google.protobuf.Empty\"!\202\323\344\223\002\033\"\031/v2/grou"
  "p/{group_id}/join\022x\n\016JoinTournament\022!.na"
  "kama.api.JoinTournamentRequest\032\026.google."
  "protobuf.Empty\"+\202\323\344\223\002%\"#/v2/tournament/{"
  "tournament_id}/join\022n\n\016KickGroupUsers\022!."
  "nakama.api.KickGroupUsersRequest\032\026.googl"
  "e.protobuf.Empty\"!\202\323\344\223\002\033\"\031/v2/group/{gro"
  "up_id}/kick\022g\n\nLeaveGroup\022\035.nakama.api.L"
  "eaveGroupRequest\032\026.google.protobuf.Empty"
  "\"\"\202\323\344\223\002\034\"\032/v2/group/{group_id}/leave\022`\n\t"
  "LinkApple\022\030.nakama.api.AccountApple\032\026.go"
  "ogle.protobuf.Empty\"!\202\323\344\223\002\033\"\026/v2/account"
  "/link/apple:\001*\022c\n\nLinkCustom\022\031.nakama.ap"
  "i.AccountCustom\032\026.google.protobuf.Empty\""
  "\"\202\323\344\223\002\034\"\027/v2/account/link/custom:\001*\022c\n\nL"
  "inkDevice\022\031.nakama.api.AccountDevice\032\026.g"
  "oogle.protobuf.Empty\"\"\202\323\344\223\002\034\"\027/v2/accoun"
  "t/link/device:\001*\022`\n\tLinkEmail\022\030.nakama.a"
  "pi.AccountEmail\032\026.google.protobuf.Empty\""
  "!\202\323\344\223\002\033\"\026/v2/account/link/email:\001*\022s\n\014Li"
  "nkFacebook\022\037.nakama.api.LinkFacebookRequ"
  "est\032\026.google.protobuf.Empty\"*\202\323\344\223\002$\"\031/v2"
  "/account/link/facebook:\007account\022\212\001\n\027Link"
  "FacebookInstantGame\022&.nakama.api.Account"
  "FacebookInstantGame\032\026.google.protobuf.Em"
  "pty\"/\202\323\344\223\002)\"$/v2/account/link/facebookin"
  "stantgame:\001*\022o\n\016LinkGameCenter\022\035.nakama."
  "api.AccountGameCenter\032\026.google.protobuf."
  "Empty\"&\202\323\344\223\002 \"\033/v2/account/link/gamecent"
  "er:\001*\022c\n\nLinkGoogle\022\031.nakama.api.Account"
  "Google\032\026.google.protobuf.Empty\"\"\202\323\344\223\002\034\"\027"
  "/v2/account/link/google:\001*\022d\n\tLinkSteam\022"
  "\034.nakama.api.LinkSteamRequest\032\026.google.p"
  "rotobuf.Empty\"!\202\323\344\223\002\033\"\026/v2/account/link/"
  "steam:\001*\022\177\n\023ListChannelMessages\022&.nakama"
  ".api.ListChannelMessagesRequest\032\036.nakama"
  ".api.ChannelMessageList\" \202\323\344\223\002\032\022\030/v2/cha"
  "nnel/{channel_id}\022Y\n\013ListFriends\022\036.nakam"
  "a.api.ListFriendsRequest\032\026.nakama.api.Fr"
  "iendList\"\022\202\323\344\223\002\014\022\n/v2/friend\022U\n\nListGrou"
  "ps\022\035.nakama.api.ListGroupsRequest\032\025.naka"
  "ma.api.GroupList\"\021\202\323\344\223\002\013\022\t/v2/group\022q\n\016L"
  "istGroupUsers\022!.nakama.api.ListGroupUser"
  "sRequest\032\031.nakama.api.GroupUserList\"!\202\323\344"
  "\223\002\033\022\031/v2/group/{group_id}/user\022\220\001\n\026ListL"
  "eaderboardRecords\022).nakama.api.ListLeade"
  "rboardRecordsRequest\032!.nakama.api.Leader"
  "boardRecordList\"(\202\323\344\223\002\"\022 /v2/leaderboard"
  "/{leaderboard_id}\022\267\001\n!ListLeaderboardRec"
  "ordsAroundOwner\0224.nakama.api.ListLeaderb"
  "oardRecordsAroundOwnerRequest\032!.nakama.a"
  "pi.LeaderboardRecordList\"9\202\323\344\223\0023\0221/v2/le"
  "aderboard/{leaderboard_id}/owner/{owner_"
  "id}\022W\n\013ListMatches\022\036.nakama.api.ListMatc"
  "hesRequest\032\025.nakama.api.MatchList\"\021\202\323\344\223\002"
  "\013\022\t/v2/match\022q\n\021ListNotifications\022$.naka"
  "ma.api.ListNotificationsRequest\032\034.nakama"
  ".api.NotificationList\"\030\202\323\344\223\002\022\022\020/v2/notif"
  "ication\022\242\001\n\022ListStorageObjects\022%.nakama."
  "api.ListStorageObjectsRequest\032\035.nakama.a"
  "pi.StorageObjectList\"F\202\323\344\223\002@\022\030/v2/storag"
  "e/{collection}Z$\022\"/v2/storage/{collectio"
  "n}/{user_id}\022i\n\017ListTournaments\022\".nakama"
  ".api.ListTournamentsRequest\032\032.nakama.api"
  ".TournamentList\"\026\202\323\344\223\002\020\022\016/v2/tournament\022"
  "\213\001\n\025ListTournamentRecords\022(.nakama.api.L"
  "istTournamentRecordsRequest\032 .nakama.api"
  ".TournamentRecordList\"&\202\323\344\223\002 \022\036/v2/tourn"
  "ament/{tournament_id}\022\262\001\n ListTournament"
  "RecordsAroundOwner\0223.nakama.api.ListTour"
  "namentRecordsAroundOwnerRequest\032 .nakama"
  ".api.TournamentRecordList\"7\202\323\344\223\0021\022//v2/t"
  "ournament/{tournament_id}/owner/{owner_i"
  "d}\022p\n\016ListUserGroups\022!.nakama.api.ListUs"
  "erGroupsRequest\032\031.nakama.api.UserGroupLi"
  "st\" \202\323\344\223\002\032\022\030/v2/user/{user_id}/group\022w\n\021"
  "PromoteGroupUsers\022$.nakama.api.PromoteGr"
  "oupUsersRequest\032\026.google.protobuf.Empty\""
  "$\202\323\344\223\002\036\"\034/v2/group/{group_id}/promote\022t\n"
  "\020DemoteGroupUsers\022#.nakama.api.DemoteGro"
  "upUsersRequest\032\026.google.protobuf.Empty\"#"
  "\202\323\344\223\002\035\"\033/v2/group/{group_id}/demote\022o\n\022R"
  "eadStorageObjects\022%.nakama.api.ReadStora"
  "geObjectsRequest\032\032.nakama.api.StorageObj"
  "ects\"\026\202\323\344\223\002\020\"\013/v2/storage:\001*\022\177\n\007RpcFunc\022"
  "\017.nakama.api.Rpc\032\017.nakama.api.Rpc\"R\202\323\344\223\002"
  "\'\"\014/v2/rpc/{id}:\007payloadZ\016\022\014/v2/rpc/{id}"
  "\222A\"b \n\017\n\013HttpKeyAuth\022\000\n\r\n\tBearerJwt\022\000\022d\n"
  "\013UnlinkApple\022\030.nakama.api.AccountApple\032\026"
  ".google.protobuf.Empty\"#\202\323\344\223\002\035\"\030/v2/acco"
  "unt/unlink/apple:\001*\022g\n\014UnlinkCustom\022\031.na"
  "kama.api.AccountCustom\032\026.google.protobuf"
  ".Empty\"$\202\323\344\223\002\036\"\031/v2/account/unlink/custo"
  "m:\001*\022g\n\014UnlinkDevice\022\031.nakama.api.Accoun"
  "tDevice\032\026.google.protobuf.Empty\"$\202\323\344\223\002\036\""
  "\031/v2/account/unlink/device:\001*\022d\n\013UnlinkE"
  "mail\022\030.nakama.api.AccountEmail\032\026.google."
  "protobuf.Empty\"#\202\323\344\223\002\035\"\030/v2/account/unli"
  "nk/email:\001*\022m\n\016UnlinkFacebook\022\033.nakama.a"
  "pi.AccountFacebook\032\026.google.protobuf.Emp"
  "ty\"&\202\323\344\223\002 \"\033/v2/account/unlink/facebook:"
  "\001*\022\216\001\n\031UnlinkFacebookInstantGame\022&.nakam"
  "a.api.AccountFacebookInstantGame\032\026.googl"
  "e.protobuf.Empty\"1\202\323\344\223\002+\"&/v2/account/un"
  "link/facebookinstantgame:\001*\022s\n\020UnlinkGam"
  "eCenter\022\035.nakama.api.AccountGameCenter\032\026"
  ".google.protobuf.Empty\"(\202\323\344\223\002\"\"\035/v2/acco"
  "unt/unlink/gamecenter:\001*\022g\n\014UnlinkGoogle"
  "\022\031.nakama.api.AccountGoogle\032\026.google.pro"
  "tobuf.Empty\"$\202\323\344\223\002\036\"\031/v2/account/unlink/"
  "google:\001*\022d\n\013UnlinkSteam\022\030.nakama.api.Ac"
  "countSteam\032\026.google.protobuf.Empty\"#\202\323\344\223"
  "\002\035\"\030/v2/account/unlink/steam:\001*\022a\n\rUpdat"
  "eAccount\022 .nakama.api.UpdateAccountReque"
  "st\032\026.google.protobuf.Empty\"\026\202\323\344\223\002\020\032\013/v2/"
  "account:\001*\022f\n\013UpdateGroup\022\036.nakama.api.U"
  "pdateGroupRequest\032\026.google.protobuf.Empt"
  "y\"\037\202\323\344\223\002\031\032\024/v2/group/{group_id}:\001*\022\212\001\n\025V"
  "alidatePurchaseApple\022(.nakama.api.Valida"
  "tePurchaseAppleRequest\032$.nakama.api.Vali"
  "datePurchaseResponse\"!\202\323\344\223\002\033\"\026/v2/iap/pu"
  "rchase/apple:\001*\022\215\001\n\026ValidatePurchaseGoog"
  "le\022).nakama.api.ValidatePurchaseGoogleRe"
  "quest\032$.nakama.api.ValidatePurchaseRespo"
  "nse\"\"\202\323\344\223\002\034\"\027/v2/iap/purchase/google:\001*\022"
  "\215\001\n\026ValidatePurchaseHuawei\022).nakama.api."
  "ValidatePurchaseHuaweiRequest\032$.nakama.a"
  "pi.ValidatePurchaseResponse\"\"\202\323\344\223\002\034\"\027/v2"
  "/iap/purchase/huawei:\001*\022\224\001\n\026WriteLeaderb"
  "oardRecord\022).nakama.api.WriteLeaderboard"
  "RecordRequest\032\035.nakama.api.LeaderboardRe"
  "cord\"0\202\323\344\223\002*\" /v2/leaderboard/{leaderboa"
  "rd_id}:\006record\022t\n\023WriteStorageObjects\022&."
  "nakama.api.WriteStorageObjectsRequest\032\035."
  "nakama.api.StorageObjectAcks\"\026\202\323\344\223\002\020\032\013/v"
  "2/storage:\001*\022\272\001\n\025WriteTournamentRecord\022("
  ".nakama.api.WriteTournamentRecordRequest"
  "\032\035.nakama.api.LeaderboardRecord\"X\202\323\344\223\002R\032"
  "\036/v2/tournament/{tournament_id}:\006recordZ"
  "(\"\036/v2/tournament/{tournament_id}:\006recor"
  "dB\247\003\n\031com.heroiclabs.nakama.apiB\rNakamaA"
  "piGrpcP\001Z\'github.com/heroiclabs/nakama/v"
  "3/apigrpc\252\002\017Nakama.Protobuf\222A\274\002\022u\n\rNakam"
  "a API v2\"_\n!The Nakama Authors & Contrib"
  "utors\022$https://github.com/heroiclabs/nak"
  "ama\032\024hello@heroiclabs.com2\0032.0\032\016127.0.0."
  "1:7350*\001\0012\020application/json:\020application"
  "/jsonZ\?\n\017\n\tBasicAuth\022\002\010\001\n\r\n\tBearerJwt\022\000\n"
  "\035\n\013HttpKeyAuth\022\016\010\002\032\010http_key \002b\017\n\r\n\tBear"
  "erJwt\022\000r:\n\033Nakama server documentation\022\033"
  "https://heroiclabs.com/docsb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_github_2ecom_2fheroiclabs_2fnakama_2fapigrpc_2fapigrpc_2eproto_deps[6] = {
  &::descriptor_table_github_2ecom_2fheroiclabs_2fnakama_2dcommon_2fapi_2fapi_2eproto,
  &::descriptor_table_google_2fapi_2fannotations_2eproto,
  &::descriptor_table_google_2fapi_2fhttp_2eproto,
  &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
  &::descriptor_table_protoc_2dgen_2dopenapiv2_2foptions_2fannotations_2eproto,
  &::descriptor_table_protoc_2dgen_2dopenapiv2_2foptions_2fopenapiv2_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_github_2ecom_2fheroiclabs_2fnakama_2fapigrpc_2fapigrpc_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_github_2ecom_2fheroiclabs_2fnakama_2fapigrpc_2fapigrpc_2eproto = {
  false, false, 9675, descriptor_table_protodef_github_2ecom_2fheroiclabs_2fnakama_2fapigrpc_2fapigrpc_2eproto, "github.com/heroiclabs/nakama/apigrpc/apigrpc.proto", 
  &descriptor_table_github_2ecom_2fheroiclabs_2fnakama_2fapigrpc_2fapigrpc_2eproto_once, descriptor_table_github_2ecom_2fheroiclabs_2fnakama_2fapigrpc_2fapigrpc_2eproto_deps, 6, 0,
  schemas, file_default_instances, TableStruct_github_2ecom_2fheroiclabs_2fnakama_2fapigrpc_2fapigrpc_2eproto::offsets,
  file_level_metadata_github_2ecom_2fheroiclabs_2fnakama_2fapigrpc_2fapigrpc_2eproto, file_level_enum_descriptors_github_2ecom_2fheroiclabs_2fnakama_2fapigrpc_2fapigrpc_2eproto, file_level_service_descriptors_github_2ecom_2fheroiclabs_2fnakama_2fapigrpc_2fapigrpc_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK ::PROTOBUF_NAMESPACE_ID::Metadata
descriptor_table_github_2ecom_2fheroiclabs_2fnakama_2fapigrpc_2fapigrpc_2eproto_metadata_getter(int index) {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_github_2ecom_2fheroiclabs_2fnakama_2fapigrpc_2fapigrpc_2eproto);
  return descriptor_table_github_2ecom_2fheroiclabs_2fnakama_2fapigrpc_2fapigrpc_2eproto.file_level_metadata[index];
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_github_2ecom_2fheroiclabs_2fnakama_2fapigrpc_2fapigrpc_2eproto(&descriptor_table_github_2ecom_2fheroiclabs_2fnakama_2fapigrpc_2fapigrpc_2eproto);
namespace nakama {
namespace api {

// @@protoc_insertion_point(namespace_scope)
}  // namespace api
}  // namespace nakama
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
